// <auto-generated />
using EXSM3942_Demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EXSM3942Demo.Migrations
{
    [DbContext(typeof(CarsContext))]
    [Migration("20230208022758_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EXSM3942_Demo.Data.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "utf8mb4");

                    b.HasKey("ID");

                    b.ToTable("manufacturer", (string)null);

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Name = "Ford"
                        },
                        new
                        {
                            ID = -2,
                            Name = "Dodge"
                        });
                });

            modelBuilder.Entity("EXSM3942_Demo.Data.Models.Model", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)")
                        .HasColumnName("id");

                    b.Property<int>("ManufacturerID")
                        .HasColumnType("int(10)")
                        .HasColumnName("manufacturer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("name")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "utf8mb4");

                    b.HasKey("ID");

                    b.HasIndex("ManufacturerID");

                    b.ToTable("model", (string)null);

                    b.HasData(
                        new
                        {
                            ID = -1,
                            ManufacturerID = -1,
                            Name = "Mustang"
                        },
                        new
                        {
                            ID = -2,
                            ManufacturerID = -1,
                            Name = "Probe"
                        },
                        new
                        {
                            ID = -3,
                            ManufacturerID = -2,
                            Name = "Challenger"
                        },
                        new
                        {
                            ID = -4,
                            ManufacturerID = -2,
                            Name = "Stealth"
                        });
                });

            modelBuilder.Entity("EXSM3942_Demo.Data.Models.Vehicle", b =>
                {
                    b.Property<string>("VIN")
                        .HasColumnType("char(17)")
                        .HasColumnName("vin")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("VIN"), "utf8mb4");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("colour")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Colour"), "utf8mb4");

                    b.Property<int>("ModelID")
                        .HasColumnType("int(10)")
                        .HasColumnName("model_id");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int(10)")
                        .HasColumnName("model_year");

                    b.HasKey("VIN");

                    b.HasIndex("ModelID");

                    b.ToTable("vehicle", (string)null);

                    b.HasData(
                        new
                        {
                            VIN = "1FABP2732GF171121",
                            Colour = "Yellow",
                            ModelID = -1,
                            ModelYear = 2008
                        },
                        new
                        {
                            VIN = "1ZVBT22L6K5103610",
                            Colour = "Blue",
                            ModelID = -2,
                            ModelYear = 1994
                        },
                        new
                        {
                            VIN = "2C3CDZGG0JH112887",
                            Colour = "Red",
                            ModelID = -3,
                            ModelYear = 2012
                        },
                        new
                        {
                            VIN = "JB3BM64JXPY011653",
                            Colour = "Silver",
                            ModelID = -4,
                            ModelYear = 1993
                        });
                });

            modelBuilder.Entity("EXSM3942_Demo.Data.Models.Model", b =>
                {
                    b.HasOne("EXSM3942_Demo.Data.Models.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Model_Manufacturer");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("EXSM3942_Demo.Data.Models.Vehicle", b =>
                {
                    b.HasOne("EXSM3942_Demo.Data.Models.Model", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Vehicle_Model");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("EXSM3942_Demo.Data.Models.Manufacturer", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("EXSM3942_Demo.Data.Models.Model", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
