// <auto-generated />
using EXSM3942_Demo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EXSM3942Demo.Migrations
{
    [DbContext(typeof(DBFirstCarsContext))]
    [Migration("20230208024534_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("EXSM3942_Demo.Models.Dealership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<int>("Manufacturerid")
                        .HasColumnType("int(11)")
                        .HasColumnName("manufacturerid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .HasColumnName("phonenumber")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Manufacturerid" }, "FK_Dealership_Manufacturer");

                    b.ToTable("dealership", (string)null);
                });

            modelBuilder.Entity("EXSM3942_Demo.Models.Efmigrationshistory", b =>
                {
                    b.Property<string>("MigrationId")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ProductVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("MigrationId")
                        .HasName("PRIMARY");

                    b.ToTable("__efmigrationshistory", (string)null);
                });

            modelBuilder.Entity("EXSM3942_Demo.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("manufacturer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            Id = -2,
                            Name = "Daihatsu"
                        },
                        new
                        {
                            Id = -3,
                            Name = "Citroen"
                        });
                });

            modelBuilder.Entity("EXSM3942_Demo.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<int>("Manufacturerid")
                        .HasColumnType("int(11)")
                        .HasColumnName("manufacturerid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Manufacturerid" }, "FK_Model_Manufacturer");

                    b.ToTable("model", (string)null);
                });

            modelBuilder.Entity("EXSM3942_Demo.Models.Vehicle", b =>
                {
                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("char(17)")
                        .HasColumnName("vin")
                        .IsFixedLength();

                    b.Property<int>("DealershipId")
                        .HasColumnType("int(11)")
                        .HasColumnName("DealershipID");

                    b.Property<int>("Modelid")
                        .HasColumnType("int(11)")
                        .HasColumnName("modelid");

                    b.Property<string>("Trimlevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("trimlevel");

                    b.HasKey("Vin")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DealershipId" }, "FK_Vehicle_Dealership");

                    b.HasIndex(new[] { "Modelid" }, "FK_Vehicle_Model");

                    b.ToTable("vehicle", (string)null);
                });

            modelBuilder.Entity("EXSM3942_Demo.Models.Dealership", b =>
                {
                    b.HasOne("EXSM3942_Demo.Models.Manufacturer", "Manufacturer")
                        .WithMany("Dealerships")
                        .HasForeignKey("Manufacturerid")
                        .IsRequired()
                        .HasConstraintName("FK_Dealership_Manufacturer");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("EXSM3942_Demo.Models.Model", b =>
                {
                    b.HasOne("EXSM3942_Demo.Models.Manufacturer", "Manufacturer")
                        .WithMany("Models")
                        .HasForeignKey("Manufacturerid")
                        .IsRequired()
                        .HasConstraintName("FK_Model_Manufacturer");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("EXSM3942_Demo.Models.Vehicle", b =>
                {
                    b.HasOne("EXSM3942_Demo.Models.Dealership", "Dealership")
                        .WithMany("Vehicles")
                        .HasForeignKey("DealershipId")
                        .IsRequired()
                        .HasConstraintName("FK_Vehicle_Dealership");

                    b.HasOne("EXSM3942_Demo.Models.Model", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("Modelid")
                        .IsRequired()
                        .HasConstraintName("FK_Vehicle_Model");

                    b.Navigation("Dealership");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("EXSM3942_Demo.Models.Dealership", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("EXSM3942_Demo.Models.Manufacturer", b =>
                {
                    b.Navigation("Dealerships");

                    b.Navigation("Models");
                });

            modelBuilder.Entity("EXSM3942_Demo.Models.Model", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
