// <auto-generated />
using EXSM3942_Demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EXSM3942Demo.Migrations
{
    [DbContext(typeof(ClassRoomContext))]
    [Migration("20230217022214_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EXSM3942_Demo.Data.Models.ClassRoom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)")
                        .HasColumnName("id");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int(10)")
                        .HasColumnName("room_number");

                    b.HasKey("ID");

                    b.ToTable("classroom", (string)null);

                    b.HasData(
                        new
                        {
                            ID = -1,
                            RoomNumber = 1001
                        },
                        new
                        {
                            ID = -2,
                            RoomNumber = 1002
                        },
                        new
                        {
                            ID = -3,
                            RoomNumber = 1003
                        });
                });

            modelBuilder.Entity("EXSM3942_Demo.Data.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)")
                        .HasColumnName("id");

                    b.Property<int>("ClassRoomID")
                        .HasColumnType("int(10)")
                        .HasColumnName("classroom_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("first_name")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("FirstName"), "utf8mb4");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("last_name")
                        .UseCollation("utf8mb4_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("LastName"), "utf8mb4");

                    b.HasKey("ID");

                    b.HasIndex("ClassRoomID")
                        .HasDatabaseName("FK_Student_ClassRoom");

                    b.ToTable("student", (string)null);

                    b.HasData(
                        new
                        {
                            ID = -1,
                            ClassRoomID = -1,
                            FirstName = "Liam",
                            LastName = "Smith"
                        },
                        new
                        {
                            ID = -2,
                            ClassRoomID = -1,
                            FirstName = "Liam",
                            LastName = "Johnson"
                        },
                        new
                        {
                            ID = -3,
                            ClassRoomID = -1,
                            FirstName = "Liam",
                            LastName = "Williams"
                        },
                        new
                        {
                            ID = -4,
                            ClassRoomID = -3,
                            FirstName = "Liam",
                            LastName = "Brown"
                        },
                        new
                        {
                            ID = -5,
                            ClassRoomID = -3,
                            FirstName = "Liam",
                            LastName = "Jones"
                        },
                        new
                        {
                            ID = -6,
                            ClassRoomID = -1,
                            FirstName = "Noah",
                            LastName = "Smith"
                        },
                        new
                        {
                            ID = -7,
                            ClassRoomID = -3,
                            FirstName = "Noah",
                            LastName = "Johnson"
                        },
                        new
                        {
                            ID = -8,
                            ClassRoomID = -2,
                            FirstName = "Noah",
                            LastName = "Williams"
                        },
                        new
                        {
                            ID = -9,
                            ClassRoomID = -1,
                            FirstName = "Noah",
                            LastName = "Brown"
                        },
                        new
                        {
                            ID = -10,
                            ClassRoomID = -2,
                            FirstName = "Noah",
                            LastName = "Jones"
                        },
                        new
                        {
                            ID = -11,
                            ClassRoomID = -2,
                            FirstName = "Oliver",
                            LastName = "Smith"
                        },
                        new
                        {
                            ID = -12,
                            ClassRoomID = -1,
                            FirstName = "Oliver",
                            LastName = "Johnson"
                        },
                        new
                        {
                            ID = -13,
                            ClassRoomID = -2,
                            FirstName = "Oliver",
                            LastName = "Williams"
                        },
                        new
                        {
                            ID = -14,
                            ClassRoomID = -2,
                            FirstName = "Oliver",
                            LastName = "Brown"
                        },
                        new
                        {
                            ID = -15,
                            ClassRoomID = -2,
                            FirstName = "Oliver",
                            LastName = "Jones"
                        },
                        new
                        {
                            ID = -16,
                            ClassRoomID = -1,
                            FirstName = "Elijah",
                            LastName = "Smith"
                        },
                        new
                        {
                            ID = -17,
                            ClassRoomID = -1,
                            FirstName = "Elijah",
                            LastName = "Johnson"
                        },
                        new
                        {
                            ID = -18,
                            ClassRoomID = -1,
                            FirstName = "Elijah",
                            LastName = "Williams"
                        },
                        new
                        {
                            ID = -19,
                            ClassRoomID = -1,
                            FirstName = "Elijah",
                            LastName = "Brown"
                        },
                        new
                        {
                            ID = -20,
                            ClassRoomID = -2,
                            FirstName = "Elijah",
                            LastName = "Jones"
                        },
                        new
                        {
                            ID = -21,
                            ClassRoomID = -2,
                            FirstName = "James",
                            LastName = "Smith"
                        },
                        new
                        {
                            ID = -22,
                            ClassRoomID = -2,
                            FirstName = "James",
                            LastName = "Johnson"
                        },
                        new
                        {
                            ID = -23,
                            ClassRoomID = -2,
                            FirstName = "James",
                            LastName = "Williams"
                        },
                        new
                        {
                            ID = -24,
                            ClassRoomID = -3,
                            FirstName = "James",
                            LastName = "Brown"
                        },
                        new
                        {
                            ID = -25,
                            ClassRoomID = -2,
                            FirstName = "James",
                            LastName = "Jones"
                        });
                });

            modelBuilder.Entity("EXSM3942_Demo.Data.Models.Student", b =>
                {
                    b.HasOne("EXSM3942_Demo.Data.Models.ClassRoom", "ClassRoom")
                        .WithMany("Students")
                        .HasForeignKey("ClassRoomID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Student_ClassRoom");

                    b.Navigation("ClassRoom");
                });

            modelBuilder.Entity("EXSM3942_Demo.Data.Models.ClassRoom", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
